# Generated by Django 4.1.2 on 2022-10-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bio',
        ),
        migrations.AddField(
            model_name='listing',
            name='authenticity',
            field=models.TextField(default='Kevin', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(default='Kevin', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery',
            field=models.CharField(default='Kevin', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='money_back',
            field=models.TextField(default='Kevin', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='payments',
            field=models.CharField(default='Kevin', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.CharField(default='Kevin', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_information',
            field=models.TextField(default='Kevin', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_details',
            field=models.CharField(default='Kevin', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='ships_from',
            field=models.CharField(default='Kevin', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.CharField(default='Kevin', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(default='Kevin', max_length=100),
        ),
    ]
