# Generated by Django 4.1.2 on 2022-10-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bio',
            field=models.TextField(default='This item is super useful', max_length=500),
        ),
    ]
